#!/usr/bin/env python3
"""Regenerates model-install's LlamaCppArchitectures.kt from a llama.cpp checkout
at the tag llama-runtime/src/main/cpp/CMakeLists.txt builds (GIT_TAG):

    git clone --depth 1 --branch <tag> https://github.com/ggml-org/llama.cpp /tmp/llama.cpp
    python3 scripts/gen_llama_architectures.py /tmp/llama.cpp

The architecture names are llama.cpp's own LLM_ARCH_NAMES table (src/llama-arch.cpp):
exactly the `general.architecture` values the bundled library can load.
LlamaCppArchitecturesTest fails when the tag in CMakeLists.txt moves without this
being rerun.
"""
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "model-install/src/main/kotlin/ai/localstudio/model/install/LlamaCppArchitectures.kt"
CMAKE = ROOT / "llama-runtime/src/main/cpp/CMakeLists.txt"

# Not models llama.cpp loads for text: placeholders and the dummy CLIP entry.
NOT_LOADABLE = {"clip", "(unknown)"}


def main():
    src = pathlib.Path(sys.argv[1])
    tag = re.search(r"GIT_TAG\s+(\S+)", CMAKE.read_text()).group(1)
    checkout_tag = subprocess.run(["git", "-C", str(src), "describe", "--tags", "--exact-match"], capture_output=True, text=True).stdout.strip()
    if checkout_tag and checkout_tag != tag:
        sys.exit(f"{src} is at {checkout_tag}, CMakeLists.txt builds {tag}")
    arch_cpp = (src / "src/llama-arch.cpp").read_text()
    table = arch_cpp[arch_cpp.index("LLM_ARCH_NAMES"):]
    table = table[: table.index("};")]
    names = [n for n in re.findall(r'\{\s*LLM_ARCH_[A-Z0-9_]+,\s*"([^"]+)"\s*\}', table) if n not in NOT_LOADABLE]
    body = ",\n".join(f'        "{n}"' for n in names)
    OUT.write_text(f'''package ai.localstudio.model.install

// GENERATED by scripts/gen_llama_architectures.py from llama.cpp {tag}
// (src/llama-arch.cpp, LLM_ARCH_NAMES). Do not edit by hand: rerun the script
// when llama-runtime/src/main/cpp/CMakeLists.txt moves to another llama.cpp tag.

/** The `general.architecture` values the bundled llama.cpp ({tag}) can load. */
object LlamaCppArchitectures {{
    const val LLAMA_CPP_TAG = "{tag}"

    val LOADABLE: Set<String> = setOf(
{body},
    )
}}
''')
    print(f"{len(names)} architectures from llama.cpp {tag} -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
