#!/usr/bin/env python3
"""Regenerates model-install's MtmdProjectors.kt from a llama.cpp checkout at
the tag llama-runtime/src/main/cpp/CMakeLists.txt builds (GIT_TAG):

    git clone --depth 1 --branch <tag> https://github.com/ggml-org/llama.cpp /tmp/llama.cpp
    python3 scripts/gen_mtmd_projectors.py /tmp/llama.cpp

The names are llama.cpp's own PROJECTOR_TYPE_NAMES table (tools/mtmd/clip-impl.h):
exactly the `clip.projector_type` values the bundled mtmd can load.
MtmdProjectorsTest fails when the tag in CMakeLists.txt moves without this being rerun.
"""
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "model-install/src/main/kotlin/ai/localstudio/model/install/MtmdProjectors.kt"
CMAKE = ROOT / "llama-runtime/src/main/cpp/CMakeLists.txt"


def main():
    src = pathlib.Path(sys.argv[1])
    tag = re.search(r"GIT_TAG\s+(\S+)", CMAKE.read_text()).group(1)
    checkout_tag = subprocess.run(["git", "-C", str(src), "describe", "--tags", "--exact-match"], capture_output=True, text=True).stdout.strip()
    if checkout_tag and checkout_tag != tag:
        sys.exit(f"{src} is at {checkout_tag}, CMakeLists.txt builds {tag}")
    header = (src / "tools/mtmd/clip-impl.h").read_text()
    table = header[header.index("PROJECTOR_TYPE_NAMES"):]
    table = table[: table.index("};")]
    names = re.findall(r'\{\s*PROJECTOR_TYPE_[A-Z0-9_]+,\s*"([^"]+)"\s*\}', table)
    body = ",\n".join(f'        "{n}"' for n in names)
    OUT.write_text(f'''package ai.localstudio.model.install

// GENERATED by scripts/gen_mtmd_projectors.py from llama.cpp {tag}
// (tools/mtmd/clip-impl.h, PROJECTOR_TYPE_NAMES). Do not edit by hand: rerun
// the script when llama-runtime/src/main/cpp/CMakeLists.txt moves to another llama.cpp tag.

/** The `clip.projector_type` values the bundled mtmd ({tag}) can load -- vision, audio and speech projectors alike. */
object MtmdProjectors {{
    const val LLAMA_CPP_TAG = "{tag}"

    val LOADABLE: Set<String> = setOf(
{body},
    )
}}
''')
    print(f"{len(names)} projector types from llama.cpp {tag} -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
