package ai.localstudio.app.phrasebook

import android.content.Context
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/**
 * A canned reply to a [Phrase] — e.g. the three price options a taxi driver
 * might quote back for [Phrase] `taxi_01`. Not a translation of the phrase
 * itself, a plausible response to it.
 */
@Serializable
data class PhrasebookAnswer(
    val id: String,
    val intent: String,
    val ru: String,
    val en: String,
    val crs: String,
    /** True only for `status: reviewed` in the source CSV — see [Phrase.verified]. */
    val verified: Boolean,
    val confidence: String,
)

@Serializable
data class Phrase(
    val id: String,
    val situation: String,
    val intent: String,
    val ru: String,
    val en: String,
    val crs: String,
    /**
     * Whether the Creole text was checked against more than one documented
     * source (`status: reviewed` in the source CSV) rather than generated by
     * pattern from vocabulary lists (`status: draft`). Shown in the UI as a
     * plain signal, not hidden — a tourist repeating an unverified phrase to
     * a taxi driver is the actual risk this exists to flag, not a reason to
     * withhold the phrase itself.
     */
    val verified: Boolean,
    val confidence: String,
    val source: String,
    val answers: List<PhrasebookAnswer>,
)

@Serializable
data class PhrasebookData(
    val situations: List<String>,
    val phrases: List<Phrase>,
)

object Phrasebook {
    private const val ASSET_PATH = "phrasebook_crs.json"
    private val json = Json { ignoreUnknownKeys = true }

    @Volatile
    private var cached: PhrasebookData? = null

    fun load(context: Context): PhrasebookData {
        cached?.let { return it }
        val text = context.assets.open(ASSET_PATH).bufferedReader(Charsets.UTF_8).use { it.readText() }
        return json.decodeFromString<PhrasebookData>(text).also { cached = it }
    }
}
